AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  limited-chat-app

  This app is sample SAM app.
  This is a chat where the log disappears in 10 minutes.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PostMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: post-message/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Policies: AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        PostMessage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /postMessage
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
        External:
          - "@aws-sdk/lib-dynamodb"
          - "@aws-sdk/client-dynamodb"
  ListMessagesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: list-messages/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Policies: AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        PostMessage:
          Type: Api 
          Properties:
            Path: /listMessages
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
        External:
          - "@aws-sdk/lib-dynamodb"
          - "@aws-sdk/client-dynamodb"
  ChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatTable
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PostMessageApi:
    Description: "API Gateway endpoint URL for Prod stage for PostMessage function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/postMessage/"
  PostMessageFunction:
    Description: "Post Message Lambda Function ARN"
    Value: !GetAtt PostMessageFunction.Arn
  PostMessageFunctionIamRole:
    Description: "Implicit IAM Role created for Post Message function"
    Value: !GetAtt PostMessageFunctionRole.Arn
  ListMessagesApi:
    Description: "API Gateway endpoint URL for Prod stage for ListMessages function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/listMessages/"
  ListMessageFunction:
    Description: "List Messages Lambda Function ARN"
    Value: !GetAtt ListMessagesFunction.Arn
  ListMessagesFunctionIamRole:
    Description: "Implicit IAM Role created for List Messages function"
    Value: !GetAtt ListMessagesFunctionRole.Arn
